-- create table OPERA
-- (
--     ID           VARCHAR2 not null,
--     NAME         VARCHAR2,
--     DESCRIPTION  VARCHAR2,
--     AGE_CATEGORY INT,
--     constraint OPERA_PK
--         primary key (ID)
-- );
--
-- create unique index OPERA_NAME_UINDEX
--     on OPERA (NAME);


-- create table opera
-- (
--     id           integer,
--     name         varchar(250),
--     description  varchar(250),
--     age_category integer
-- );
--
-- alter table opera
--     owner to postgres;
--
